### ISSUE TITLE
update github repository and github organization api to support project-console github organization manager view

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#1390]
- add project_sfid to github repository and github organization table
- use this project_sfid to add/delete/list in all v2 github organization and github repositories api
- update list project github organization api to provide all repositories with connection_status

**Comment by nirupamav** [comment]
As per discssuion with @prasannamahajan, below API's needs to be tested in this ticket and also regression in V1 is required for project console

1. https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getProjectGithubOrganizations
2. https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/addProjectGithubOrganization
3. https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/deleteProjectGithubOrganization
4. https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/addProjectGithubRepository
5. https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/deleteProjectGithubRepository

**Comment by nirupamav** [comment]
**1. When all repositories under the github org are deleted, github org status is returned as partial_connection instead of connection_failure**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/85b6ed1a-04df-474c-ba03-13304d20037e)

**2. When repositories that are added to the project are deleted in github still the repository details are fetched in endpoint that fetch repositories for the project.**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4987fa59-23d7-4767-be63-4437f1bdba06)

**3. When repository is made private, repository status is connected. When repository is private we cannot even access the repo until we have access to the repo**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/feda5114-d3a1-4f7d-a875-e77fce61c6aa)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a313f748-524f-44a3-a53e-297750ffbd87)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/125b0bbd-42bb-4f27-be8d-0b2410bb70f7)

**4. Issues with email notification sent when repository is deselected from easycla bot in github. Email is not formatted. Also in the instructions point 2 should be changed to Installed GitHub Apps**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9e121135-8461-4a61-9395-16b62e94e498)

**5. While adding github repositories, github org is case sensitive**
Add github org with capital letters
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7050a418-e306-4c7c-98bd-5ac95b5ebe36)
Add github repositories with githuborg in small letters
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ae02bbde-1430-458b-a0a3-39750faa7659)
Now if I give the same case that I used while adding githug org then it works
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8d7bf631-16f1-4ea4-9832-22d895bb37c4)


**6. 200 with empty list is returned instead of 404 when invalid projectsfid is provided (I provided companysfid and tried) while fetching github org or github repositories**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6957d96d-60d8-4eb4-80f0-48e5af527824)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c80e0f08-93f1-40fe-97e4-dddec440dbea)

**7. Able to add repository which does not belong to the github org. I randomly gave an Id and it was added to the project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/aab60145-5786-48b8-a956-96d670cb81cf)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/144f07a0-95c3-44c8-8dbf-b6e4898135bb)

**8. Appropriate error message is not displayed when invalid repositoryid is provided while adding github repository**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/81780dc4-2c68-47ce-a08a-f330d7aafec9)

**9. 422 is returned instead of 400 when empty object or when all mandatory fields are not provided in the payload while adding github repository**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/83a3ec9b-e9e5-4b72-b7b9-844a852392a6)

**10. Appropriate error message is not displayed when trying to delete github org with invalid projectsfid or invalid githuborg name or invalid combination of valid projectsfid and githuborg while deleting github org**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c68e5b0a-308f-415b-b676-37092a7a75c9)

**Comment by nirupamav** [comment]
If I find any more bugs will update the ticket with the issues

**Comment by nirupamav** [comment]
Verified and observed that Issue11 in https://app.zenhub.com/workspaces/easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/1390#issuecomment-662409585  is fixed

**Comment by prasannamahajan** [comment]
@nirupamav @dealako

1. When all repositories under the github org are deleted, github org status is returned as partial_connection instead of connection_failure
A : This is not a bug. Since easycla app is still installed it is partial_connection

2. When repositories that are added to the project are deleted in github still the repository details are fetched in endpoint that fetch repositories for the project.
A : Updated the delete cla-group endpoint to delete github repositories linked with it  

3. When repository is made private, repository status is connected. When repository is private we cannot even access the repo until we have access to the repo
A: Even though repository is private, easycla github app will still have access of it.

4. Issues with email notification sent when repository is deselected from easycla bot in github. Email is not formatted. Also in the instructions point 2 should be changed to Installed GitHub Apps
A: #todo

5. . While adding github repositories, github org is case sensitive
A: #todo. Need to add index on github organization table (organization_name_lower) and use it for query

6.  200 with empty list is returned instead of 404 when invalid projectsfid is provided (I provided companysfid and tried) while fetching github org or github repositories
A: #todo. This should not happen as we use acs to check permission. we should also remove getProjectGithubRepositories endpoint from v2 as 
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getProjectGithubOrganizations is sufficient

7. Able to add repository which does not belong to the github org. I randomly gave an Id and it was added to the project
A: #todo : Need to add validation, check if this github repo is part of provided github org

8. Appropriate error message is not displayed when invalid repositoryid is provided while adding github repository
A: #todo : 

9. 9. 422 is returned instead of 400 when empty object or when all mandatory fields are not provided in the payload while adding github repository
A: This is valid scenario. Whenever client doesnt follow swagger spec, swagger generated server will return 422. 

10. Appropriate error message is not displayed when trying to delete github org with invalid projectsfid or invalid githuborg name or invalid combination of valid projectsfid and githuborg while deleting github org
A: #todo

11. Observed that in below scenario github organization status is returned as connection_failure instead of connected
A: Fixed.

**Comment by dealako** [comment]
@rinkeshbhutwala can you review and pick up this ticket. Some are resolved, some need further work.  Thanks!

**Comment by nirupamav** [comment]
**4. Issues with email notification sent when repository is deselected from easycla bot in github. Email is not formatted. Also in the instructions point 2 should be changed to Installed GitHub Apps**
`Issue is still reproducible`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/450f9ade-2062-49ba-9d76-92e3e309f70c)

**6. 200 with empty list is returned instead of 404 when invalid projectsfid is provided (I provided companysfid and tried) while fetching github org or github repositories**
`Issue is still reporducible for github repositories`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1de4f130-46a1-4a50-aa61-004567ae827d)
`Verified that 404 is returned however appropriate message is not returned. However appropriate message is not displayed. ProjectId is not found. But message says github org not found`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b6d92a5d-57d7-45b0-9792-8d00dd79f921)


**_Below issues are fixed and working as expected_**
**2. When repositories that are added to the project are deleted in github still the repository details are fetched in endpoint that fetch repositories for the project.**
`Verified that the issue is fixed `

**5. While adding github repositories, github org is case sensitive**
`Verified that the issue is fixed and now github org is not case sensitive while adding repos`

**7. Able to add repository which does not belong to the github org. I randomly gave an Id and it was added to the project**
`Verified that 400 with appropriate message is returned`

**8. Appropriate error message is not displayed when invalid repositoryid is provided while adding github repository**
`Verified that 400 with appropriate message is returned`

**10. Appropriate error message is not displayed when trying to delete github org with invalid projectsfid or invalid githuborg name or invalid combination of valid projectsfid and githuborg while deleting github org**
`Verified that the issue is fixed`

**11. Observed that in below scenario github organization status is returned as connection_failure instead of connected**
`Verified that the issue is fixed`
I added a github org
installed easycla app
So now the status is returned connected in the endpoint to fetch github org which is as expected
I now uninstalled easycla app
so the status returned is connection_failure which is as expected
Now I again installed easycla app
But still the status is connection_failure instead connected should be returned

**Comment by nirupamav** [comment]
**Verified**
**_Issue4_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e4bafded-b0a4-4743-8322-cf045b43659c)

**_Issue6 - 403 is returned for invalid projectId_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/742ba725-81af-4560-a1ad-410558d2c104)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d6826198-1ade-4661-8ece-ed84779a1c42)

**_Issue12_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4652a88e-fa9e-4428-9fcd-f370a4d52280)
