### ISSUE TITLE
V2 - get cla groups endpoint returns empty list when queried by projectsfid

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1623]
**Observed that empty list is returned when trying to fetch cla groups for the project. This is a scenario when CLA group is at project level**

Foundation
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/foundation/a0941000005osNmAAI/cla-groups
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/632bc511-bd49-4b6f-95eb-8bccc45f8b09)

Project under foundation
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/foundation/a0917000009T9jvAAC/cla-groups
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/13ccfb66-c5ba-4416-8d01-cde97a6a9185)

**Comment by dealako** [comment]
@rinkeshbhutwala I made some updates to these APIs late last week. Can you coordinate with @nirupamav on test scenarios to confirm this was fixed and working as expected. If possible, can we add a unit or functional test?

**Comment by dealako** [comment]
@rinkeshbhutwala [review the code in the service layer](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/v2/cla_groups/service.go#L707):

Determine if the caller provided `foundationID` value is a "Project Group" (previously called a Foundation) or "Project". You can determine this by looking this up in the Platform Project Service.

1. If it is a foundation, execute code as implemented - no change in behavior.
1. If a project, perform a lookup of the associated CLA Group and return results that match the schema output (will be only one in the list) - new behavior.

This way, this API call will work with a "Project Group" or "Project".

// CC @wanyaland

**Comment by nirupamav** [comment]
**Tested and observed below issues**

**_Project Level CLA Group_**
1. When queried by foundationsfid, list of 2 CLA groups is displayed. However same CLA Group data is displayed for both the list values
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/foundation/a091700000ARkggAAD/cla-groups

2. When queried by child project projectsfid, foundationLevelCLA flag is shown as true
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/foundation/a091700000ARkgqAAD/cla-groups

3. When queries by foundationsfid or by  child project projectsfid, projectlist object has both the child projects
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a0d25d38-e9ae-4b5a-9c83-2f2c22bf25c0)

**Comment by dealako** [comment]
One more try - updated create and fetch logic.

PR: https://github.com/communitybridge/easycla/pull/1750

**Comment by nirupamav** [comment]
**Issue is still reproducible. Which is impacting the UI in thet way the CLA Groups are shown**

**_Project Level - I had created CLA Groups Bug2392Child1 and Bug2392Child2. However two records for Bug2392Child1 is fetched and each record has both project list when triggered getCLAGroup endpoint_**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/foundation/a091700000ARqt4AAD/cla-groups
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/30d51525-d0a3-431f-b2c1-84e8130b63d4)

**Comment by rinkeshbhutwala** [comment]
@nirupamav I have fixed the **duplicate** cla-group response and tested on **DEV** with the above example its works fine.

**Comment by dealako** [comment]
With @rinkeshbhutwala updates and [this PR](https://github.com/communitybridge/easycla/pull/1757) we should be set now. @nirupamav please validate.

**Comment by nirupamav** [comment]
@rinkeshbhutwala 
**_Duplicate CLA Group ID is fixed however project_list lists all projects under that foundation for a project_**

**When I created CLA Group for a project below is the response, where there is only one project in project_list which is as expected (CLA Group is created at project Level)**
```
{
    "ccla_enabled": true,
    "ccla_pdf_url": "https://cla-signature-files-dev.s3.amazonaws.com/contract-group/41396aa0-a5e3-4971-9dab-a4b674c2ac1e/template/ccla.pdf",
    "ccla_requires_icla": true,
    "cla_group_description": "Description ProjectLevel2childprojectsChild2",
    "cla_group_id": "41396aa0-a5e3-4971-9dab-a4b674c2ac1e",
    "cla_group_name": "ProjectLevel2childprojectsChild2",
    "foundationLevelCLA": false,
    "foundation_name": "ProjectLevel2childprojectsParent",
    "foundation_sfid": "a0902000000A2DGAA0",
    "icla_enabled": true,
    "icla_pdf_url": "https://cla-signature-files-dev.s3.amazonaws.com/contract-group/41396aa0-a5e3-4971-9dab-a4b674c2ac1e/template/icla.pdf",
    "project_list": [
        {
            "project_name": "ProjectLevel2childprojectsChild2",
            "project_sfid": "a0902000000A2DQAA0",
            "repositories_count": 0
        }
    ],
    "repositories_count": 0,
    "root_project_repositories_count": 0,
    "total_signatures": 0
}
```

**When I fetch with get endpoint project_list lists all projects under the foundation** 
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/foundation/a0902000000A2DQAA0/cla-groups
```
{
    "list": [
        {
            "ccla_enabled": true,
            "ccla_pdf_url": "https://cla-signature-files-dev.s3.amazonaws.com/contract-group/41396aa0-a5e3-4971-9dab-a4b674c2ac1e/template/ccla.pdf",
            "ccla_requires_icla": true,
            "cla_group_description": "Description ProjectLevel2childprojectsChild2",
            "cla_group_id": "41396aa0-a5e3-4971-9dab-a4b674c2ac1e",
            "cla_group_name": "ProjectLevel2childprojectsChild2",
            "foundationLevelCLA": false,
            "foundation_name": "ProjectLevel2childprojectsParent",
            "foundation_sfid": "a0902000000A2DGAA0",
            "icla_enabled": true,
            "icla_pdf_url": "https://cla-signature-files-dev.s3.amazonaws.com/contract-group/41396aa0-a5e3-4971-9dab-a4b674c2ac1e/template/icla.pdf",
            "project_list": [
                {
                    "project_name": "ProjectLevel2childprojectsChild1",
                    "project_sfid": "a0902000000A2DLAA0",
                    "repositories_count": 0
                },
                {
                    "project_name": "ProjectLevel2childprojectsChild2",
                    "project_sfid": "a0902000000A2DQAA0",
                    "repositories_count": 0
                }
            ],
            "repositories_count": 0,
            "root_project_repositories_count": 0,
            "total_signatures": 0
        }
    ]
}
```

**Comment by nirupamav** [comment]
Verified and observed that data is fetched as expected when queried by foundationsfid or projectsfid for below user cases
1. CLA Group for Standalone project
2. CLA Group at foundation level
3. CLA Group at project level with 1 CLA group for each project
4. CLA Group at project level with 1 CLA group having multiple projects
