### ISSUE TITLE
FINOS : Found duplicate entry under APPROVED CONTRIBUTORS list for "The Linux foundation" organization at FINOS project 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3055]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab 
3. Search Organization "The linux foundation"
4. Click on View All Approved Contributors

Actual Results :  duplicate entry under APPROVED CONTRIBUTORS list for "The Linux foundation" organization at FINOS project 

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/f6c6e002-5fc0-4002-8e3c-87d6d0fcc116)

**Comment by nickmango** [comment]
Resolved . kindly verify @thakurveerendras

**Comment by thakurveerendras** [comment]
Duplicate entry are removed but following issue appears for above org 
- Now below user entry is missing 
1. Andrey Kozlov
2. Linux Foundation bot
3. Vasu Naidu

- Unknow not listed user data under finos sheet also appears 
1.  James McLeod

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a13c690a-2261-4345-ad90-b10da0182530)

**Comment by thakurveerendras** [comment]
Issue is retested & found following behavior

1. **Andrey Kozlov** user appears two time with wrong GitHub id 
2. **Dan Kohn user** GitHub id is missing
3. **Chris Aniszczyk & Dan Kohn** user user LFID shown while this user doesn't have LFID in FINOS sheet
4. **Vasu** is incomplete name, it should be **Vasu Naidu**
5. **Linux Foundation bot** detail is still missing 

QA-Failed for above cases 

Actual : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a71ccdb2-de4b-4020-b649-002050b34d58)
Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/12d2d7a0-1431-429f-945d-9c699ff0f0bf)

**Comment by thakurveerendras** [comment]
Hi @nickmango , Issue retested & found following behavior

- Unknow user data found : James McLeod & Dan Kohn
- User data Missing : Andrey Kozlov
- Linux Foundation bot GitHub id is wrong 

Actual : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/6afe761f-c12e-4e4b-9797-478e05bffe5c)
Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/844c1f1d-e24b-4778-90e9-8292b408f887)

**Comment by thakurveerendras** [comment]
Name filed is missing for below user

1. Andrey Kozlov
2. The Linux Foundation

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/5559d7f0-b30c-4411-98e8-1eac9550d07f)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify

**Comment by thakurveerendras** [comment]
Wrong plexus-user details appears for organization 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/f54b0101-6515-4fa2-b23a-61169be70bb4)

**Comment by thakurveerendras** [comment]
plexus-user details is removed form organization, So making issue status QA-Done 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/644b7eb5-d873-485e-8c3e-41463b752802)
