### ISSUE TITLE
EasyCLA Bug Report: Confusing project information in new administrator notice

### ISSUE THREAD

**Issue by jberkus** [communitybridge/easycla#3498]
## Summary

When new administrators are notified via email of their status, the project named in the notification email is incorrect.

## Background

1. Added a new administrator for Red Hat, project CNCF.
2. The new admin received an email that said this:

"You have been added as a CLA Manager for the organization Red Hat, Inc. and the project OpenTelemetry. This means that you can now maintain the list of employees allowed to contribute to the project OpenTelemetry on behalf of your company, as well as view and manage the list of your company’s CLA Managers for the CLA Group Cloud Native Computing Foundation (CNCF)."

This is incorrect; the added administrator has permissions over signers for the entire CNCF (which they should).  Nor are there any specific permissions associated with the OpenTelemetry project.

## Expected behavior

The email should have said:

"You have been added as a CLA Manager for the organization Red Hat, Inc. for the CLA Group Cloud Native Computing Foundation (CNCF)."

## Environment

Please complete the following information:

* Environment:
  - [ ] PROD 
  - [ ] 
* Browser:
  - Not applicable

**Comment by jberkus** [comment]
This appears to be a more general bug where any email about our CNCF-level permissions gets attributed to OpenTelemetry instead.  We just got another email:

```
This is a notification email from EasyCLA regarding the project OpenTelemetry.

q () has been removed as a CLA Manager from Red Hat, Inc. for the project OpenTelemetry.
```

**Comment by WillsonHG** [comment]
This has been added to our tracker and we will be investigating the issue.

**Comment by mlehotskylf** [comment]
@jberkus we believe this issue has been resolved. Can you please confirm this issue is no longer occurring?
Thank you!

**Comment by nickmango** [comment]
@mlehotskylf  This could be an issue down to the type of CLA signed up for (If foundation signed CLA then we should maintain the mail at the parent level, in case of project signed CLA then the specific projects need to be used in the email)

**Comment by jberkus** [comment]
I cannot verify it until I get another notice, which doesn't happen at regular intervals.

**Comment by thakurveerendras** [comment]
@mlehotskylf , @nickmango , The Issue is still reproducible as reported on the dev site. Kindly update the email text as mentioned in expected section above

![image](https://github.com/communitybridge/easycla/assets/75417507/20064cbb-5397-437b-8802-e46b0fdebd0f)

**Comment by jberkus** [comment]
This is still broken.

I just had to remove an administrator today, and got the attached: 

![image](https://github.com/communitybridge/easycla/assets/115146/f4fa9c08-97cb-4078-959a-75fe5f2a795d)

**Comment by nickmango** [comment]
Noted @jberkus . Will have this updated

**Comment by nickmango** [comment]
@thakurveerendras kindly verify this
context is the cla_group_id has to be signed at the foundation level..(at least there has to be association between foundation and cla_group, which should be the case for the Sun project)

**Comment by thakurveerendras** [comment]
Tested on dev site & found that proper (parent) project name appears while added/deleted PM from enrolled child project 

Refer to the screenshot

![image](https://github.com/communitybridge/easycla/assets/75417507/1bfce5a7-1297-4ec7-a2fe-32db4e3a709b)
![image](https://github.com/communitybridge/easycla/assets/75417507/146ca88e-698a-49f0-80d1-cc9374884bc2)

**Comment by jberkus** [comment]
Will do. I can only test it by adding/removing an administrator, which is not something I can casually do without informing management.

**Comment by mlehotskylf** [comment]
Thank you @jberkus for letting us know and sorry for the delay. We will take a look at this shortly.

**Comment by nickmango** [comment]
@thakurveerendras kindly review.

**Comment by thakurveerendras** [comment]
Hi @nickmango 
Cla-group name is wrong for the child project in the email, it is showing the parent project cla-group name

- Parent project: SUN, 
> CLA-Group name: Sun foundation cla group.

- Child project: Earth, 
> CLA-Group name: earth child cla group

I have added cla-manager to child project & mail received for foundation project 
![image](https://github.com/user-attachments/assets/0c81ed86-f0a9-4ead-818d-2edd5dc91bac)
![image](https://github.com/user-attachments/assets/a5a3ced2-b046-40c0-ae9c-620633e6cb8b)

**Comment by mlehotskylf** [comment]
@nickmango is working on PR. @thakurveerendras please re-verify once merged.

**Comment by nickmango** [comment]
@thakurveerendras Kindly reverify - focus on child projects has been deprecated and CLA Group Naming will be used in the email body

**Comment by thakurveerendras** [comment]
Hello @nickmango , @mlehotskylf 
It is still failing for the notice received at the existing cla-manager on the child project

|Project: CLA-Manger  | Email Subject |Status |Screenshot|
| ------------- | ------------- |------------- |------------- |
|  Parent project : SUN - Existing cla-manger |  EasyCLA: CLA Manager Added Notice for Sun foundation cla group  | Passed  |![image](https://github.com/user-attachments/assets/dadb7cbf-d2aa-42cd-a930-17caa58475cc)  |
|  Parent project: SUN -Newly added cla-manager |  EasyCLA: CLA Manager Added Notice for Sun foundation cla group  |Passed  |![image](https://github.com/user-attachments/assets/fa7781e1-96d5-4f8a-a694-1894ae870898)  |
|  Child project: Earth - Existing cla-manger   | EasyCLA: CLA Manager Added Notice for earth child cla group  | Failed: SUN project cla-group details appears  |![image](https://github.com/user-attachments/assets/9b30f73c-2871-4b94-bf18-6da14a3610bf)  |
|  Child project: Earth -Newly added cla-manager   |  EasyCLA: Added as CLA Manager for Project :earth child cla group  |Passed  |![image](https://github.com/user-attachments/assets/bb391907-1097-4792-92eb-3a47e6f71c9b)  |

**Comment by thakurveerendras** [comment]
Hello @nickmango 
Tested failed case & found that it is working fine, So updating this ticket status 

Refer to the screenshot
![image](https://github.com/user-attachments/assets/d4d7afd5-4688-4f96-a6e6-6ca5b100f000)

**Comment by mlehotskylf** [comment]
Closing as fixed.
