### ISSUE TITLE
GitHub @web-flow user added at easycla check on GitHub PR

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3903]
## Summary

Foreign @web-flow user added at easycla check on GitHub PR

## Background

1. Clone repo on local system
2. Add git branch : git checkout -b coauth14
3. Made some changes on file
4. git add .
5. git commit -m "Add commit by auth" --author "thakurveerendras1 [veerendrat+1@proximabiz.com](mailto:veerendrat+1@proximabiz.com)" --signoff
6. git push origin coauth14
7. Made some changes on file again
8. git add .
9. git commit -m "test Co-auth" -m "Co-authored-by: vrthakur [thakur.viren17@gmail.com](mailto:thakur.viren17@gmail.com)"
10. git push origin coauth14
11. Login GitHub via user thakurveerendras1
12. Change in file & create PR

## Actual Results 

Foreign @web-flow user added at easycla check on GitHub PR

## Expected behavior

 @web-flow user should ignore on PR

## Screenshots
![image](https://user-images.githubusercontent.com/75417507/232977949-f594e517-c77a-4313-92d6-43ce12ac72a4.png)

## Environment

* Environment:
  - [ ] ALL
  - [x] DEV
  - [ ] STAGING
  - [x] PROD

**Comment by thakurveerendras** [comment]
Tested issue at dev site & found that web-flow not added after follow co-author steps, So making issue status QA-Passed at dev site

- PR : https://github.com/sun-test-org/repo1/pull/50

Refer screenshot 
![image](https://user-images.githubusercontent.com/75417507/233145890-d67ffc79-83c3-40fa-94d9-f1f66714d6fc.png)

**Comment by WillsonHG** [comment]
Just to add some context here to the issue for everyone, this is related to the change we made in https://github.com/communitybridge/easycla/issues/3884 to catch more edge cases of co-authors and co-committers. We released this early this morning, and we see that the GitHub bot web-flow is now getting tagged by easycla for authorization. So to unblock PRs, we've manually added authorization for that bot, but the longterm fix will be to ignore it going forward.

**Comment by dmikusa** [comment]
The project I'm working with has got a dozen or more PRs where the bot has incorrectly flagged the web-flow bot. What steps, if any, do we need to take to get the bot to reevaluate & approve the PR? Thanks

**Comment by trask** [comment]
@dmikusa this is working for us again now, see if adding a PR comment `/easycla` to re-trigger the EasyCLA check works for you

**Comment by dmikusa** [comment]
Still happening for us as recently as two hours ago: https://github.com/paketo-buildpacks/pipeline-builder/pull/1109

I tried `/easycla` too but it doesn't seem to have had an impact. https://github.com/paketo-buildpacks/oracle/pull/120#issuecomment-1515485839

**Comment by WillsonHG** [comment]
Hi @dmikusa  it should be working now for you with the /easycla comment for the Paketo org (and any CFF org), apologies for the delay with this.

**Comment by dmikusa** [comment]
Thanks @WillsonHG - I'm not seeing this issue on new PRs any longer, however, I can't seem to get `/easycla` to work. I add a comment on the issue, but it never seems to do anything. I don't know how long it typically takes. I waited a few minutes though, without any update. It's not a big deal we're working around the stuck PRs already, just curious how long that usually takes.
