### ISSUE TITLE
Signature ID appears when invalidated (approved set to false) email address

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3945]
## Summary

Signature ID appears when invalidated (approved set to false) email address

## Steps
1. Login admin portal 
2. Search & open SUN project 
3. Click on easycla 
4. Add new Email address under approval list
5. Now delete email address form approval list

## Actual behavior
Signature ID appears when invalidated (approved set to false) email address

> Signature ID: cf6b7168-b51d-4bcf-8270-7b1d013e0ce4 invalidated (approved set to false) due to Email: hwanyama@contractor.linuxfoundation.org approval removal for the CLA Group Sun foundation cla group for the project sun for the company Infosys Limited by the user (vthakur) Singh@Thakur.

## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/838e6c5d-7774-4076-a02b-28b682ca4df7)

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
What should be the correct event summary in this case ?

**Comment by umeshlumbhani247** [comment]
Submitted the PR 
@mlehotskylf @thakurveerendras 
https://github.com/communitybridge/easycla/pull/3947

**Comment by thakurveerendras** [comment]
Wrong Approval Criteria appears tooltips 

- Project link : https://lfx.dev.platform.linuxfoundation.org/foundation/a09P000000DsCE5IAN/cla

![image](https://github.com/communitybridge/easycla/assets/75417507/dac61f24-353f-40c8-9947-3565b5bed07c)

**Comment by umeshlumbhani247** [comment]
@thakurveerendras  This is a existing issue of tool-tip, I have just fixed it.

**Comment by mlehotskylf** [comment]
Additional PR: https://github.com/communitybridge/easycla/pull/3951

**Comment by thakurveerendras** [comment]
@umeshlumbhani247 ,  now no reason string appears at activity log after remove GitHub user from approval list 
![image](https://github.com/communitybridge/easycla/assets/75417507/91781207-2505-4b57-84f5-cc612a1049b5)

**Comment by thakurveerendras** [comment]
Still showing no reason in event for GitHub user (User not exist), 

- Try to delete GitHub user vthakur from approval list 

![image](https://github.com/communitybridge/easycla/assets/75417507/e4b29379-f796-4432-ba7d-af8ac40a8553)

**Comment by mlehotskylf** [comment]
QA in DEV done, waiting for PROD deployment.
